name: Build Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  store_image_reference:
    runs-on: ubuntu-latest
    steps:
      - name: Create an artifact with image-ref data
        env:
          IMAGE_REF: "test_image_ref"
          IMAGE: "test_image"
          IMAGE_TAG: "test_tag"
        run: |
          printf '{
            "image-ref": "%s",
            "image": "%s",
            "image-tag": "%s"
          }' $IMAGE_REF $IMAGE $IMAGE_TAG >> context.json
      - uses: actions/upload-artifact@v4
        with:
          name: context.json
          path: ./
          retention-days: 3
          overwrite: true

  call_another_workflow:
    name: Call another jobs
    needs: store_image_reference
    uses: syarmoliuk/test/.github/workflows/deploy.yml@main